# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'getoptlong'
gem 'logger'
gem 'uri'
gem 'nokogiri'
gem 'json'
gem 'colorize'
